name: LizZusev
favicon: null
layout_spectrum: 0.75433
typography_spectrum: 0.25023511704057455
title: LizZusev
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e3e3e3'
    - '#404040'
    - '#6a6a6a'
    - '#b0b0b0'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
